#!/usr/bin/env ruby

args = ARGV.join(' ')
feature_args, cucumber_args = *(args.split('--').map { |string| string.split(' ') })
cucumber_args ||= []

cucumber_args += feature_args.map do |arg|
  name, line = *arg.strip.split(':')
  line = ":#{line}" if line
  "features/#{name}.feature#{line}"
end

script = if File.directory?(".bundle")
           cucumber_args.unshift("exec", "cucumber")
           "bundle"
         elsif File.executable?('script/cucumber')
           'script/cucumber'
         else
           'cucumber'
         end


ENV['CUCUMBER_FORMAT'] ||= 'pretty'

puts "CUCUMBER_FORMAT=#{ENV['CUCUMBER_FORMAT']} #{script} #{cucumber_args.join(' ')}"
exec(script, *cucumber_args)
